name: web CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        run: git clone https://github.com/muddasir883/ci-cd-.git

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install python3
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          cd ci-cd-
          python3 -m pip install Flask

      - name: Run Tests
        run: |
          cd ci-cd-
          nohup python3 test.py > /dev/null 2>&1 &
          sleep 5  # Adjust as needed


    

