name: web CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3]

    steps:

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          sudo apt-get update
          sudo apt-get install python3
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install Flask

      - name: Run Tests
        run: |
          nohup python3 test.py > /dev/null 2>&1 &
          sleep 5  # Adjust as needed

      - name: Stop Python server
        run: |
          lsof -ti :5000 | xargs kill -9 || true

