name: web CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install Flask

      - name: Run Tests
        run: |
          nohup python3 test.py > /dev/null 2>&1 &  # Run in background and redirect output
          sleep 5  # Give time for the server to start

      # Add a step to stop the Python server after running tests
      - name: Stop Python server
        run: |
          lsof -ti :5000 | xargs kill -9 || true  # Replace 5000 with the port your Flask server listens on
      
